Repository AppScale/appscale-tools, pull requests merged in 2018-10, with the labels that each got.

#697 Include handlers in Admin API Version create call
  appscale/tools/admin_api/client.py
  appscale/tools/admin_api/handler.py
  appscale/tools/admin_api/version.py
  appscale/tools/appengine_helper.py
  appscale/tools/appscale_tools.py
  test/test_appscale_upload_app.py
  test/test_version.py
Labels: Priority: High, Status: Approved for merge

#714 Create load balancer VMs in an availability set
  appscale/tools/agents/azure_agent.py
Labels: Status: Build pending, Status: Demo requested

#716 Include scaling information from app.yaml or appengine-web.xml for version create
  appscale/tools/admin_api/client.py
  appscale/tools/admin_api/version.py
Labels: Status: Demo requested

#721 Use managed availability set for adding VMs created with managed disks
  appscale/tools/agents/azure_agent.py
Labels: Status: Demo requested
