Repository AppScale/appscale-tools, pull requests merged in 2018-02, with the labels that each got.

#673 RM-565 - Script to automate version bump
  Makefile
  util/bump_version.sh
Labels: Status: Demo requested

#637 Dont disable autoscale
  appscale/tools/parse_args.py
Labels: Priority: HIGH, Status: Awaiting changes

#679 Use project flag
  appscale/tools/appscale.py
  appscale/tools/appscale_tools.py
  appscale/tools/parse_args.py
  appscale/tools/remote_helper.py
  appscale/tools/scripts/appscale.py
  test/test_appscale_upload_app.py
Labels: Priority: HIGH, Status: Approved for merge
